# Generated by Django 4.2.4 on 2023-10-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(default=0, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(max_length=150, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
